# Site settings

title: R Addict Blog #kosinski.r-addict.com # Title of your site
email: m.p.kosinski@gmail.com # Your contant email
name: "http://r-addict.com"

description: > # this means to ignore newlines until "baseurl:"
    Data Scientist with 10 years of experience in machine learning, survival analysis, R programming, online recommendations, text mining and market research. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://r-addict.com" # the base hostname & protocol for your site
baseurlknitr: "/"

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

github_username:      MarcinKosinski  # Replace this with your GitHub username
linkedin_username:    mkosinski  # Replace this with your LinkedIn username
stackoverflow_usernumber: 3857701 # stackoverflow user numer :) my own invention

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
highlighter: rouge


# Disqus comments:
disqus:           true
shortname:        r-addict

# Social Media
twitter:          true # add a twitter button to each post
facebook:         true # add a facebook share button to each post
linkedin:         true # my own button
googleplus:       true # my own button
facebooklike:     true # my own

author:
  name:           'Marcin Kosiński'
  email:          'm.p.kosinski@gmail.com'

plugins:
  - jekyll-feed  
  - rouge

# Permalinks
permalink: /:year/:month/:day/:title.html

github:
  repo:           https://github.com/MarcinKosinski/MarcinKosinski.github.io
